name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: echo "Validating tests"

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image 
        run: echo "docker build -t myuser/myapp:latest ."

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v4
      - name: Publish Docker image to Docker Hub
        run: echo "docker push myuser/myapp:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: publish-docker-image
    steps:
      - uses: actions/checkout@v4
      - name: Create deployment
        run: echo "kubectl apply -f deployment.yaml"

  validate-app-deployment:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Run deployment tests 
        run: echo "kubectl rollout status deployment/myapp"
